server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  #    hostname: localhost #eureka服务端的实例名称 这只适用与单服务器 多服务器如上所示用具体名字比较好
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己
    fetch-registry: false  #false表示自己端就是注册中心 不需要检索服务
    service-url:
      defaultZone: http://eureka7002.com/eureka/  #另一个(或多个 用，隔开)服务器端的url
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   同样只适用于单机 同上hostname
