server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com

  #    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己
    fetch-registry: false  #false表示自己端就是注册中心 不需要检索服务
    service-url:
      defaultZone: http://eureka7001.com/eureka/  #另一个(或多个 用，隔开)服务器端的url
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
