server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: Horlly.test.SpringCloud.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept #它将是作为客户端微服务入驻Eureka服务端时显示的名字
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/clouddb02?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    #    schema:
    #       - classpath:sql/department.sql
    #       - classpath:sql/employee.sql


    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


#spring:
#  application:
#    name: microservicecloud-dept
#    datasource:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/clouddb01?useUnicode=true&amp;characterEncoding=utf8
#      username: root
#      password: 123456
#      initialization-mode: always
#      dbcp2:
#      min-idle: 5
#      initial-size: 5
#      max-total: 5
#      max-wait-millis: 200

eureka:
  client:   #客户端
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群写法
#      defaultZone: http://localhost:7001/eureka 单机版写法
  instance: #直接显示下面的instance-id 不再使用默认命名方式（一般是本机名字（Mxxx xxx或者干脆就是localhost）：+ 本客户端名字）
    instance-id: microservicecloud-dept8001  #改成ABCD啥的都随便
    prefer-ip-address: true #鼠标移到本客户端名字上时 屏幕左下角由显示本机名字+ 端口号（这里是8001）改为显示本机ip+ 端口号（8001）


#<!--在eureka网页上点击此客户端时 设置跳转的页面 使其不再显示error page
#            PS: 不仅仅修改此客户端pom 总的父工程也有做相应修改噢 请关注
#
#         以下为第三部分 -->
#错误页映射为info 我们这里给info加上自己设置的参数 让它不再显示不友好的默认错误页信息
info:
 app.name: Horlly-microservicecloud
 build.artifactId: ${project.artifactId}$
 build.version: ${project.version}$
 otherInfo: 没了

#不知道为啥 我上面$$内的信息没显示 本来是不用加{ }的 弹幕说加了就ok 我加了也没用。
#又有弹幕说重新build一下项目 不要直接重启main函数才会显示 我不想重启 我懒的一批 反正差不多功能通了就行我感觉 刚学的时候这么在乎细枝末节干嘛是吧hhhhh兴趣为主。
